[package]
name = "nannou_audio"
version ="0.18.0"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]
description = "The audio API for Nannou, the creative coding framework."
readme = "README.md"
keywords = ["audio", "stream", "cross-platform", "dsp", "pcm"]
license = "MIT"
repository = "https://github.com/nannou-org/nannou_audio.git"
homepage = "https://nannou.cc"
edition = "2018"

[dependencies]
cpal = "0.13.1"
dasp_sample = "0.11.0"
thiserror = "1"

[features]
# FIXME: I had to disable this because it kept interfering with nannou_nokhwa's bindgen. Someone please tell CPAL to update asio bindgen to 0.56
#asio = ["cpal/asio"]
